# Generated by Django 4.1.4 on 2022-12-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_rename_phone_no_student_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_id',
            new_name='stud_ID',
        ),
    ]
